sonar.projectName=UsahainAja Backend
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=db/migrations/**,cmd/**,coverage.out
sonar.coverage.exclusions=cmd/**,**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
